In [22]:
import torch


#TODO: Write initialisation version of this
#Data Starts with respective owners A and B
x_dataA = torch.Tensor([[10.0], [9.0], [3.0], [2.0]])
y_dataA = torch.Tensor([[90.0], [80.0], [50.0], [30.0]])

x_dataB = torch.Tensor([[7.0], [8.0], [3.0], [1.0]])
y_dataB = torch.Tensor([[60.0], [70.0], [40.0], [20.0]])

data_federation = [[x_dataA, y_dataA], [x_dataB, y_dataB]]

in_layer = 1
out_layer = 1

optimizer = "SGD"
criterion = "MSELoss"

starting_model = torch.rand((in_layer, out_layer))

epochs = 1
learn_rate = 0.05

In [23]:
starting_model

tensor([[0.2074]])

In [24]:
from sail_safe_functions.machine_learning.LinearRegressionTrain import LinearRegressionTrain

trained_model = LinearRegressionTrain.run(in_layer, out_layer, epochs, data_federation[0], learn_rate, starting_model, criterion, optimizer)

Model Parameters: tensor([179.1834])
Loss: tensor([17149.1719])


In [25]:
trained_models = []

for i in range(10):
    starting_model = torch.rand(in_layer, out_layer)
    trained_models.append(LinearRegressionTrain.run(in_layer, out_layer, epochs, data_federation[0], learn_rate, starting_model, criterion, optimizer))

Model Parameters: tensor([179.1863])
Loss: tensor([17149.7324])
Model Parameters: tensor([171.0237])
Loss: tensor([15599.9414])
Model Parameters: tensor([176.8932])
Loss: tensor([16706.6504])
Model Parameters: tensor([166.4473])
Loss: tensor([14764.4424])
Model Parameters: tensor([180.9697])
Loss: tensor([17498.5000])
Model Parameters: tensor([164.6746])
Loss: tensor([14447.2676])
Model Parameters: tensor([177.1895])
Loss: tensor([16763.5664])
Model Parameters: tensor([174.5153])
Loss: tensor([16253.5391])
Model Parameters: tensor([178.5433])
Loss: tensor([17024.8887])
Model Parameters: tensor([178.7896])
Loss: tensor([17072.6602])


In [26]:
trained_models

[tensor([179.1863]),
 tensor([171.0237]),
 tensor([176.8932]),
 tensor([166.4473]),
 tensor([180.9697]),
 tensor([164.6746]),
 tensor([177.1895]),
 tensor([174.5153]),
 tensor([178.5433]),
 tensor([178.7896])]

In [27]:
from sail_safe_functions.machine_learning.ModelAverage import ModelAverage

avg_model = ModelAverage.run(trained_models)
avg_model

tensor([174.8233])

In [28]:
trained_models = []

for j in range(len(data_federation)):
    trained_models.append(LinearRegressionTrain.run(in_layer, out_layer, epochs, data_federation[j], learn_rate, avg_model, criterion, optimizer))
avg_model = ModelAverage.run(trained_models)
print("Avg Model: "+str(avg_model))


Model Parameters: tensor([-3033.7483])
Loss: tensor([5307302.5000])
Model Parameters: tensor([-1863.5033])
Loss: tensor([3378166.7500])
Avg Model: tensor([-2448.6257])


In [29]:
from sail_safe_functions.machine_learning.LinearRegressionRetrieve import LinearRegressionRetrieve

model = LinearRegressionRetrieve.run( 
        in_layer,
        out_layer,
        learn_rate,
        criterion,
        optimizer,
        avg_model,
    )

In [30]:
data_federation[0][0]

tensor([[10.],
        [ 9.],
        [ 3.],
        [ 2.]])

In [31]:
model.train_model(2, data_federation[0][0], data_federation[0][1])

Loss: tensor([3.9685e+11])
